In [1]:
import numpy as np

In [2]:
np.random.seed(1)
A_prev = np.random.randn(2, 4, 4, 3)
hparameters = {"stride" : 2, "f": 3}

In [68]:
def get_im2col_indices(x_shape, field_height, field_width, padding=1, stride=1):
    # First figure out what the size of the output should be
    N, C, H, W = x_shape
    assert (H + 2 * padding - field_height) % stride == 0
    assert (W + 2 * padding - field_height) % stride == 0
    out_height = int((H + 2 * padding - field_height) / stride + 1)
    out_width = int((W + 2 * padding - field_width) / stride + 1)

    i0 = np.repeat(np.arange(field_height), field_width)
    i0 = np.tile(i0, C)
    i1 = stride * np.repeat(np.arange(out_height), out_width)
    j0 = np.tile(np.arange(field_width), field_height * C)
    j1 = stride * np.tile(np.arange(out_width), out_height)
    i = i0.reshape(-1, 1) + i1.reshape(1, -1)
    j = j0.reshape(-1, 1) + j1.reshape(1, -1)

    k = np.repeat(np.arange(C), field_height * field_width).reshape(-1, 1)

    return (k.astype(int), i.astype(int), j.astype(int))


def im2col_indices(x, field_height, field_width, padding=1, stride=1):
    """ An implementation of im2col based on some fancy indexing """
    # Zero-pad the input
    p = padding
    x_padded = np.pad(x, ((0, 0), (0, 0), (p, p), (p, p)), mode='constant')

    k, i, j = get_im2col_indices(x.shape, field_height, field_width, padding, stride)

    cols = x_padded[:, k, i, j]
    C = x.shape[1]
    cols = cols.transpose(1, 2, 0).reshape(field_height * field_width * C, -1)
    return cols


def col2im_indices(cols, x_shape, field_height=3, field_width=3, padding=1,
                   stride=1):
    """ An implementation of col2im based on fancy indexing and np.add.at """
    N, C, H, W = x_shape
    H_padded, W_padded = H + 2 * padding, W + 2 * padding
    x_padded = np.zeros((N, C, H_padded, W_padded), dtype=cols.dtype)
    k, i, j = get_im2col_indices(x_shape, field_height, field_width, padding, stride)
    cols_reshaped = cols.reshape(C * field_height * field_width, -1, N)
    cols_reshaped = cols_reshaped.transpose(2, 0, 1)
    np.add.at(x_padded, (slice(None), k, i, j), cols_reshaped)
    if padding == 0:
        return x_padded
    return x_padded[:, :, padding:-padding, padding:-padding]

def conv_forward(X, W, b, stride=1, padding=1):
    cache = W, b, stride, padding
    n_filters, d_filter, h_filter, w_filter = W.shape
    n_x, d_x, h_x, w_x = X.shape
    h_out = (h_x - h_filter + 2 * padding) / stride + 1
    w_out = (w_x - w_filter + 2 * padding) / stride + 1

    if not h_out.is_integer() or not w_out.is_integer():
        raise Exception('Invalid output dimension!')

    h_out, w_out = int(h_out), int(w_out)

    X_col = im2col_indices(X, h_filter, w_filter, padding=padding, stride=stride)
    W_col = W.reshape(n_filters, -1)

    out = W_col @ X_col + b
    out = out.reshape(n_filters, h_out, w_out, n_x)
    out = out.transpose(3, 0, 1, 2)

    cache = (X, W, b, stride, padding, X_col)

    return out, cache


def conv_backward(dout, cache):
    X, W, b, stride, padding, X_col = cache
    n_filter, d_filter, h_filter, w_filter = W.shape

    db = np.sum(dout, axis=(0, 2, 3))
    db = db.reshape(n_filter, -1)

    dout_reshaped = dout.transpose(1, 2, 3, 0).reshape(n_filter, -1)
    dW = dout_reshaped @ X_col.T
    dW = dW.reshape(W.shape)

    W_reshape = W.reshape(n_filter, -1)
    dX_col = W_reshape.T @ dout_reshaped
    dX = col2im_indices(dX_col, X.shape, h_filter, w_filter, padding=padding, stride=stride)

    return dX, dW, db

In [36]:
def zero_pad(img, pad):
    return np.pad(img, ((pad, pad), (pad, pad), (0, 0)), 'constant', constant_values=(0, 0))

def naive_img2col(image, f, pad, stride):
    pass

In [82]:
x1 = np.random.randn(1, 3, 3)
x2 = np.random.randn(1, 3, 3)
x = np.array([x1, x2])
#x = np.reshape(x, newshape=(-1, -1, 2, 2))

In [83]:
x

array([[[[-0.51634791,  0.3511169 , -0.06877046],
         [-1.34776494,  1.47073986,  0.33722094],
         [ 1.00806543,  0.78522692, -0.66486777]]],


       [[[-1.94504696, -0.91542437,  1.22515585],
         [-1.05354607,  0.81604368, -0.61240697],
         [ 0.39310924, -1.82391985,  1.16707517]]]])

In [85]:
im2col_indices(x, 2, 2, 0, 1)

array([[-0.51634791, -1.94504696,  0.3511169 , -0.91542437, -1.34776494,
        -1.05354607,  1.47073986,  0.81604368],
       [ 0.3511169 , -0.91542437, -0.06877046,  1.22515585,  1.47073986,
         0.81604368,  0.33722094, -0.61240697],
       [-1.34776494, -1.05354607,  1.47073986,  0.81604368,  1.00806543,
         0.39310924,  0.78522692, -1.82391985],
       [ 1.47073986,  0.81604368,  0.33722094, -0.61240697,  0.78522692,
        -1.82391985, -0.66486777,  1.16707517]])

In [87]:
x1 = np.random.randn(1, 3, 3)
x2 = np.random.randn(1, 3, 3)
x = np.array([x1])

In [88]:
x

array([[[[-0.0396687 ,  0.8858258 ,  0.18986165],
         [ 0.7980638 , -0.10193204,  0.74335654],
         [-1.50957268, -1.08071069,  0.725474  ]]]])

In [89]:
im2col_indices(x, 2, 2, 0, 1)

array([[-0.0396687 ,  0.8858258 ,  0.7980638 , -0.10193204],
       [ 0.8858258 ,  0.18986165, -0.10193204,  0.74335654],
       [ 0.7980638 , -0.10193204, -1.50957268, -1.08071069],
       [-0.10193204,  0.74335654, -1.08071069,  0.725474  ]])

In [90]:
w = np.random.randn(3, 1, 2, 2)

In [91]:
w

array([[[[ 1.07125243, -1.09715436],
         [ 0.83863475, -1.03918232]]],


       [[[ 0.73302323, -1.89881206],
         [-1.11711069, -0.50897228]]],


       [[[-0.16648595,  1.42361443],
         [ 0.90399917,  1.57546791]]]])

In [92]:
w.reshape(3, -1)

array([[ 1.07125243, -1.09715436,  0.83863475, -1.03918232],
       [ 0.73302323, -1.89881206, -1.11711069, -0.50897228],
       [-0.16648595,  1.42361443,  0.90399917,  1.57546791]])

In [ ]:
# https://stackoverflow.com/questions/30109068/implement-matlabs-im2col-sliding-in-python
# https://stackoverflow.com/questions/30109068/implement-matlabs-im2col-sliding-in-python/31404264#31404264